Secure API with OAuth2/Connect or UMA (configurable) #168
GluuFederation/oxauth-config pull request #171
Opened 2020-09-30 13:09 UTC by pujavs

OpenID Connect API Code for review.

2020-09-30 15:02 UTC, yuriyz requested changes

2020-09-30 15:02 UTC, yuriyz commented on src/main/java/org/gluu/configapi/filters/AuthorizationFilter.java
> +            Response authorizationResponse = this.validateToken(token, resourceInfo);
Response is not returned outside somehow.

2020-09-30 15:02 UTC, yuriyz commented on src/main/java/org/gluu/configapi/filters/AuthorizationFilter.java
> +    private Response validateToken(String token, ResourceInfo resourceInfo) throws Exception {
This method looks redundant since it makes nothing.

2020-09-30 15:02 UTC, yuriyz commented on src/main/java/org/gluu/configapi/service/OpenIdService.java
> +        } catch (IOException ex) {
Exception should be logged by logger.

2020-09-30 15:02 UTC, yuriyz commented on src/main/java/org/gluu/configapi/service/OpenIdService.java
> +            throw new ConfigurationException("Failed to load oxAuth OpenId configuration");
Add inner exception inside : `throw new ConfigurationException("Failed to load oxAuth OpenId configuration", e);`.

2020-10-01 03:08 UTC, pujavs commented on pom.xml.bak
> +<?xml version="1.0"?>
This might have got created automatically. Have removed it .

2020-10-01 03:14 UTC, pujavs commented on src/main/java/org/gluu/configapi/configuration/ConfigurationFactory.java.bak
> +package org.gluu.configapi.configuration;
This might have got created automatically. Have removed it .

2020-10-01 03:18 UTC, pujavs commented on src/main/java/org/gluu/configapi/auth/OpenIdAuthorizationService.java
> +            response = getErrorResponse(Status.INTERNAL_SERVER_ERROR, "No authorization header found");
Agreed, changes done validate if token is missing and exit early with 'UNAUTHORIZED' error.

2020-10-01 03:22 UTC, pujavs commented on src/main/java/org/gluu/configapi/configuration/ConfigurationFactory.java
> +           if(ConfigurationFactory.getConfigAppPropertiesFile().equals("oauth2"))
Done

2020-10-01 03:29 UTC, pujavs commented on src/main/java/org/gluu/configapi/filters/AuthorizationFilter.java
> +            Response authorizationResponse = this.validateToken(token, resourceInfo);
Added code to validate response and exit 
![image](https://user-images.githubusercontent.com/43700552/94762119-78cb6100-03c4-11eb-9ebc-c40c9c31076b.png)

2020-10-01 03:34 UTC, pujavs commented on src/main/java/org/gluu/configapi/filters/AuthorizationFilter.java
> +    private Response validateToken(String token, ResourceInfo resourceInfo) throws Exception {
Removed redundant method and directly made call to authorizationService

2020-10-01 03:35 UTC, pujavs commented on src/main/java/org/gluu/configapi/service/OpenIdService.java
> +        } catch (IOException ex) {
Done

2020-10-01 03:36 UTC, pujavs commented on src/main/java/org/gluu/configapi/service/OpenIdService.java
> +            throw new ConfigurationException("Failed to load oxAuth OpenId configuration");
Done

2020-10-02 08:20 UTC, yuriyz requested changes

2020-10-02 08:20 UTC, yuriyz commented on src/main/java/org/gluu/configapi/auth/OpenIdAuthorizationService.java
> +        IntrospectionResponse introspectionResponse = openIdService.getIntrospectionService()
`.introspectToken("Bearer " + token, token). `. If we send "invalid_token" then it's always invalid.

2020-10-02 08:20 UTC, yuriyz commented on src/main/java/org/gluu/configapi/auth/OpenIdAuthorizationService.java
> +            logger.error("Token is Invalid !!!!!!");
remove this `!!!!!`. Just put `Token is invalid.`.
Otherwise nice work, early exit makes it much more readable.

2020-10-02 08:20 UTC, yuriyz commented on src/main/java/org/gluu/configapi/auth/OpenIdAuthorizationService.java
> +            logger.error("Inadequate Authorization !!!!!!");
logger.trace("Insufficient scopes. Required scope: " + resourceScopes + ", token scopes: " + introspectionResponse.getScope());

2020-10-02 09:21 UTC, yuriyz approved these changes

2020-10-02 09:21 UTC, merged